### PR TITLE
Dashboard version

### PR DESCRIPTION
**Pull request by ehill17**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issue(s)
Issue: <#110 >

## Steps to Test
1. Deploy branch to robot
2. Check smart dashboard on driver station

## Changelog

Added smart dashboard print statements. Config robot and swerverobot

## What?

Read from deploy.json and wrote to smart dashboard

## Why?

To ease debugging and better understand robot

### CODE REVIEW

**Review by DarthCooper — DISMISSED** [review]

**Review by ChrisHirsch — COMMENTED** [review]
Let's get this on a bot and try it out!

**Comment by jtdurham** [comment]
Deployed code to minibot using 2024 versions, commented out swerve drive train to confirm version print functionality. Smart Dashboard showed deploy values as expected.

Note that deploy.json is now placed within a py/ folder in the home directory instead of directly within the home directory itself

**Review by Sydmen — APPROVED** [review]
Looks good. +1

**Review by DanteSGarrett — APPROVED** [review]
Looks good!

**Pull request merged**
